# Aula 02 - Python

# Dados Númericos


In [3]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)
# aqui o codigo deu um valor para a
# pediu para exibir a informação 'valor de a', transformando-o em um string positivo
# ainda, pediu qual o tipo de informação é 'a', o codigo resultou que é um inteiro

Valor de a = 1


int

In [8]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)
# aqui o codigo deu um valor para b
# pediu para exibir a informação 'valor de b'
# ainda, pediu qual o tipo de informação é 'b' 
# o codigo resultou que é uma variavel real

1.0


float

In [9]:
# Converter float para int
c = int(b)
print(c)
type(c)
# definiu-se c como sendo o numero inteiro da variavel b
# pediu para exibir c e seu tipo

1


int

In [12]:
# Declarando nan
import numpy as np
d = np.nan
print(d)
type(d)
# importou uma biblioteca de codigo aberto para fazer operações
# nan significa que é um valor inválido na operação

nan


float

In [16]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)
# multiplica valor de d por 1 como 'e', resultando em nan
# tenta somar o valor de d(que é nan) a 1, resulta nan
# usa a função nansum para transformar o valor nan, presente em d em zero
# e então somar d com o 1, resultando em 1

nan
nan
1.0


# Dados de Texto

In [26]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)
# define valor pra f e g como string Fabio e Gabriel
# imprime valor da variavel f e depois da variavel g
# imprime soma de f e g
# imprime soma de f, o texto espaço e g 

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


# Dados tipo Bool- Lógica

In [25]:
a==1
# O '==' faz a comparação dos valores para verificar se são iguais
# Retorna verdadeiro ou falso

True

In [27]:
h = (a==1)
print(h)
type(h)
# 'h' recebe true, pois 'a' é igual a 1
# bool são valores booleanos (verdadeiro ou falso)

True


bool

In [28]:
h = (a==2)
print(h)
type(h)
# retornou falso, pois o 'h' já tinha valor 1

False


bool

In [29]:
i = True
type(i)
# definiu i como um valor booleano e pediu o seu tipo

bool

In [30]:
ii = 'True'
type(ii)
# quando entre aspas, a variavel que armazena é string

str

# Operação de Comparação

In [31]:
# Operação ==
a==b
# verificação se 'a' é igual a 'b', retorna true

True

In [33]:
# Operação ><
a>b
# verificação se a é maior que b

False

In [34]:
# Operação !=
a!=b
# verificação se 'a' é diferente de 'b'

False

In [35]:
# Operação >= ou <=
a>=b
# Verificação se 'a' é maior ou igual a 'b'

True

# Operações Matemáticas

In [36]:
# Soma 
a+b
# soma de a e b

2.0

In [37]:
# Soma e atribui valor
ab = a+b
print(ab)
# resulta o valor da variavel ab

2.0


In [38]:
# Multiplicação
l = a*b # Não use l como variável # l pode se confundir com 1
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [39]:
# Divisão
a/b
# faz operação de divisão entre os valores de a e b

1.0

In [40]:
# Potencia
5**2
# eleva 5 na potência quadrada

25

In [42]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)
# importou módulo math, que calcula o valr de e na potencia 10

22026.465794806718

In [43]:
# e elevado na potencia zero
math.exp(0)

1.0

In [46]:
# e elevado na potencia a, que é 1
math.exp(a)

2.718281828459045

In [47]:
math.exp(-10)
# e elevado na potencia menos 10

4.5399929762484854e-05

In [49]:
import math as mt
mt.log(c)
# importou biblioteca math e pediu pra calcular o log de c
# c não teve um valor atribuido

0.0

In [50]:
# 10 elevado a potencia de 2 é 100
mt.log10(100)

2.0

# Listas

In [51]:
# criou uma lista com os valores de 1,2 e 3 e imprimiu a lista
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [52]:
# Acessando valores da lista pelo index
print(myFirstList[0]) # acessou o valor 0 da lista, que é 1
print(myFirstList[2]) # acessou o valor 2 da lista que é 3

1
3


In [53]:
myFirstList==a
# a lista não pode ser igual a 'a'

False

In [54]:
# o valor zero da lista é 1, sendo igual a 'a'
myFirstList[0]==a

True

In [55]:
# criou uma segunda lista com a variavel 'a' dentro
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [56]:
# o tipo de váriavel é list
type(mySecList)

list

In [59]:
# o tipo de variavel do elemento 2 da lista é string
type(mySecList[2])

str

In [60]:
# o tipo de variavel do elemento 1 da lista é inteiro
type(mySecList[1])

int

# Caminhos = path


In [69]:
# prefixo r desconsidera caracteres especiais, tranformando em normais
# "C:\CPA\ENS5173_24-1_fla"
path = r"C:\CPA\ENS5173_24-1_fla"
print(path)

C:\CPA\ENS5173_24-1_fla


In [71]:
path = "C:/CPA/ENS5173_24-1_fla"
print(path)

C:/CPA/ENS5173_24-1_fla


In [72]:
import os
# Listar arquivos na pasta
os.listdir(path)
# import os significa que será feita uma interação com o sistema operacional
# listdir identifica os arquivos no diretório que está no caminho

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [73]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [75]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]
# usado para garantir que o cod funcione corretamente em outros sistemas operacionais

'C:/CPA/ENS5173_24-1_fla/.git'

In [76]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [82]:
# Diretório que estou trabalhando
os.getcwd()
# essa função retorna diretorio que o python ta sendo executado

'C:\\CPA\\ENS5173_24-1_fla\\venv\\Scripts'

In [84]:
# Mudo de diretório para o caminho 
os.chdir('C:\\CPA\\')
#C:/CPA/

In [87]:
os.getcwd()
# retorna diretório atual de trabalho

'C:\\CPA'

In [93]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    
# criou diretorio novo já que ele não existia
# rodei de novo e imprimiu que diretorio é existente

diretório já existe


In [94]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

# criou diretorio novo já que ele não existia
# rodei de novo e imprimiu que diretorio é existente

diretório já existe


# Numpy arrays e Pandas DataFrames

In [97]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)
# criou variavel numpy matriz 'n' com valor escalar de 0

numpy.ndarray

In [99]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)
# criou um array numpy com a lista, sendo cada um array numpy

[ 1  2  3 10 20 55]


In [101]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)
# matriz de 10x10 com numeros aleatorios entre 0 e 1

[[0.33044044 0.84570698 0.23452239 0.56762515 0.07616677 0.90943134
  0.78544855 0.87217973 0.54793391 0.27204068]
 [0.38811812 0.44754607 0.51145719 0.01709822 0.80081769 0.1467038
  0.51222068 0.48051776 0.25770496 0.0872671 ]
 [0.42331064 0.26951845 0.44826933 0.65687441 0.39097762 0.47571024
  0.11930114 0.6795128  0.53285248 0.70376466]
 [0.6819871  0.71068569 0.29993132 0.37882488 0.80771314 0.93333218
  0.84851564 0.73038075 0.57405004 0.4236747 ]
 [0.64368782 0.13002048 0.85209877 0.01592487 0.8972322  0.08176325
  0.87231991 0.92972166 0.54607881 0.9660557 ]
 [0.6591712  0.81483332 0.21096774 0.3247346  0.92405997 0.89579237
  0.30113634 0.48819303 0.34448493 0.24007914]
 [0.99768232 0.41097165 0.50339224 0.3530622  0.12526365 0.38450529
  0.06487622 0.2721953  0.16983203 0.59804692]
 [0.16683538 0.46956351 0.35902018 0.75437464 0.20096108 0.89759049
  0.73673831 0.41906067 0.29936117 0.06867242]
 [0.63800379 0.39254537 0.71429042 0.98486418 0.59344248 0.71146775
  0.62047279 

In [103]:
#acessa primeira linha da matriz, : significa que são todos os elementos
# Acessando valores da matriz
n[0,:]

array([0.33044044, 0.84570698, 0.23452239, 0.56762515, 0.07616677,
       0.90943134, 0.78544855, 0.87217973, 0.54793391, 0.27204068])

In [105]:
# acessando primeira coluno com todos os elementos
n[:,0]

array([0.33044044, 0.38811812, 0.42331064, 0.6819871 , 0.64368782,
       0.6591712 , 0.99768232, 0.16683538, 0.63800379, 0.92175861])

In [107]:
# acessa todas as linhas, mas sem a primeira coluna
n[:,1:5]

array([[0.84570698, 0.23452239, 0.56762515, 0.07616677],
       [0.44754607, 0.51145719, 0.01709822, 0.80081769],
       [0.26951845, 0.44826933, 0.65687441, 0.39097762],
       [0.71068569, 0.29993132, 0.37882488, 0.80771314],
       [0.13002048, 0.85209877, 0.01592487, 0.8972322 ],
       [0.81483332, 0.21096774, 0.3247346 , 0.92405997],
       [0.41097165, 0.50339224, 0.3530622 , 0.12526365],
       [0.46956351, 0.35902018, 0.75437464, 0.20096108],
       [0.39254537, 0.71429042, 0.98486418, 0.59344248],
       [0.08223755, 0.61999815, 0.31647604, 0.93619314]])

In [108]:
# acessa primeira linha e colunas da segunda a quinta
n[0,1:5]

array([0.84570698, 0.23452239, 0.56762515, 0.07616677])

In [109]:
# acessa ultimo elemento da primeira linha
n[0,-1]

0.2720406793734761

In [113]:
#acessa primeira linha na quinta coluna, até penultimo elemento da linha
n[0,4:-1]

array([0.07616677, 0.90943134, 0.78544855, 0.87217973, 0.54793391])

In [114]:
# acessa primeira linha, quinta coluna, até final da linha
n[0,4:]

array([0.07616677, 0.90943134, 0.78544855, 0.87217973, 0.54793391,
       0.27204068])

In [117]:
an = np.log(n*5)
print(an)
# calculo do log de cada elemento multiplicado por 5
# an é a nova matriz

[[ 0.50210908  1.44185557  0.15923371  1.04314389 -0.96539211  1.51450214
   1.36793759  1.47267815  1.0078373   0.30763425]
 [ 0.66299236  0.80546211  0.93894651 -2.45934297  1.38731595 -0.30990177
   0.94043818  0.87654683  0.253498   -0.82934378]
 [ 0.74978891  0.29831947  0.80707687  1.18917548  0.67033296  0.86649155
  -0.51666645  1.22305871  0.97992724  1.25812665]
 [ 1.22669338  1.26791289  0.40523615  0.63875668  1.3958896   1.5404438
   1.44517115  1.29524861  1.05439921  0.75064858]
 [ 1.16889649 -0.43062542  1.44938508 -2.53043516  1.50099733 -0.89448954
   1.47283886  1.53656788  1.00444595  1.57490413]
 [ 1.19266592  1.4046662   0.05338785  0.48469088  1.53045961  1.49939129
   0.40924574  0.89239352  0.54373298  0.18265125]
 [ 1.60711755  0.72020687  0.9230523   0.56832689 -0.46789666  0.65364019
  -1.12583623  0.30820244 -0.16350746  1.09535185]
 [-0.18130978  0.85348619  0.58506123  1.32757175  0.0047939   1.50139658
   1.30391539  0.73969834  0.40333341 -1.06896972]
 